const {execFileSync}=require('node:child_process');
const fs=require('node:fs');
for(const f of ['src/index.js','config.js','package.json']) if(!fs.existsSync(f)) throw new Error('Missing '+f);
execFileSync(process.execPath,['--check','src/index.js'],{stdio:'inherit'});
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const source=fs.readFileSync('src/index.js','utf8');
if((source.match(/client\\.login\\(process\\.env\\.DISCORD_TOKEN\\)/g)||[]).length!==1) throw new Error('Expected one login call');
if(source.includes('}\\\\nif (!Number.isInteger')) throw new Error('Escaped newline corruption');
if(!source.includes("setName('leaderboard')")) throw new Error('Leaderboard missing');
if(!source.includes("setName('economy-top')")) throw new Error('Economy leaderboard missing');
if(!source.includes("setName('automod-rule')")) throw new Error('AutoMod rule management missing');
if(!source.includes("setName('economy-admin')")) throw new Error('Economy admin controls missing');
if(!source.includes('guildAuditLogEntryCreate')) throw new Error('Audit protection missing');
if(!source.includes('Ticket Auto-Closed')) throw new Error('Ticket inactivity missing');
if(!source.includes('delete db.tickets[c.id]')) throw new Error('Ticket cleanup missing');
const names=[...source.matchAll(/new SlashCommandBuilder\\(\\)\\.setName\\('([^']+)'\\)/g)].map(m=>m[1]);
const duplicates=names.filter((n,i)=>names.indexOf(n)!==i);
if(duplicates.length) throw new Error('Duplicate slash commands: '+[...new Set(duplicates)].join(', '));
if(pkg.engines?.node!==' >=20.0.0'.trim()) throw new Error('Node engine mismatch');
console.log('Project One smoke checks: OK');
